name: t-cells-cov
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - bowtie=1.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cffi=1.14.5
  - charset-normalizer=2.0.12
  - colorama=0.4.4
  - cryptography=37.0.2
  - cycler=0.10.0
  - cython=0.29.24
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.3.0
  - fastx_toolkit=0.0.14
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.68.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jdcal=1.4.1
  - jedi=0.17.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20210714
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=11.2.0
  - libgtextutils=0.7
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - littleutils=0.2.2
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - mpmath=1.2.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.5.1
  - nose=1.3.7
  - notebook=6.3.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openpyxl=3.0.7
  - openssl=1.1.1o
  - outdated=0.2.1
  - packaging=20.9
  - pandas=1.2.3
  - pandas-flavor=0.2.0
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.1
  - patsy=0.5.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pingouin=0.5.1
  - pip=21.0.1
  - plastid=0.5.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=22.0.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - readline=8.1
  - requests=2.28.0
  - scikit-learn=0.24.1
  - scipy=1.8.0
  - seaborn=0.11.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.35.2
  - statsmodels=0.13.2
  - tabulate=0.8.9
  - terminado=0.9.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - twobitreader=3.1.7
  - typing_extensions=4.2.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xarray=2022.3.0
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - biopython==1.79
    - future==0.18.2
    - heatmapz==0.0.4
    - progressbar2==3.53.1
    - pygam==0.8.0
    - pysam==0.17.0
    - python-utils==2.5.6
    - termcolor==1.1.0
    - upsetplot==0.6.0
    - xgboost==1.3.3
    - xlrd==1.2.0
